# Verifying Python Version

In [2]:
import sys
print(sys.version)

3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)]


# Verifying Pytorch Version

In [3]:
import torch
print(torch.__version__)

0.4.1


# Working with Tensors in Pytorch

Refer [Pytorch in 60 Minutes](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#getting-started) for more details

## Creating Different Types of Tensors

Read [PyTorch Tensor Creation Ops](https://pytorch.org/docs/stable/torch.html#tensor-creation-ops) for more details.

In [13]:
# Creating An Empty Tensor
empty_tensor = torch.empty(5, 3)
print(empty_tensor)

tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000]])


In [14]:
# Randomly Initializing a Tensor
random_tensor = torch.rand(5, 3)
print(random_tensor)

tensor([[0.5415, 0.1129, 0.4736],
        [0.5595, 0.5823, 0.6142],
        [0.3889, 0.7198, 0.6705],
        [0.9722, 0.3098, 0.1098],
        [0.6523, 0.1987, 0.7557]])


In [18]:
# Creating a zero Tensor
zero_tensor = torch.zeros(5, 3, dtype=torch.long)
print(zero_tensor)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


## Performing Operations on Tensors

Refer [Pytorch Tensors](https://pytorch.org/docs/stable/torch.html) for detailed information about all types of operations that can be performed with tensors

In [22]:
# Adding Two Tensors
x = torch.rand(5, 3)
y = torch.rand(5, 3)
print(y)
print(x + y)

# Normal Operations performed on Tensors always creates a new tensor. For mutating the same tensor, functions
# ending with '_' are used. Read More about these in the documentation referenced above. Although, these in-place operations
# should be avoided generally since can mess up with backpropagation which we will read about in a future class.
y.add_(x)
print(y)

tensor([[0.2609, 0.5766, 0.4453],
        [0.0429, 0.7031, 0.4776],
        [0.0019, 0.7373, 0.1882],
        [0.6670, 0.7843, 0.8049],
        [0.1575, 0.6519, 0.8745]])
tensor([[0.7967, 1.0257, 1.2761],
        [0.4084, 1.0586, 0.8303],
        [0.1071, 1.6263, 0.7579],
        [0.9433, 1.5213, 0.8640],
        [0.3034, 0.6576, 1.2055]])
tensor([[0.7967, 1.0257, 1.2761],
        [0.4084, 1.0586, 0.8303],
        [0.1071, 1.6263, 0.7579],
        [0.9433, 1.5213, 0.8640],
        [0.3034, 0.6576, 1.2055]])


In [21]:
# Mean of a Tensor 
# Refer https://pytorch.org/docs/stable/torch.html#torch.mean for learning the different parameters
# that can be passed to the torch.mean() function

x = torch.rand(5, 3)
mean = torch.mean(x)
print(mean)

tensor(0.4826)


In [6]:
# Squaring all elements of a Tensor
x = torch.rand(5,3)
print("Original Matrix")
print(x)

# Multiple ways of performing the square operation.
print("Output of performing x**2")
print(x**2)

print("Output of performing x*x")
print(x*x)

print("Output of performing torch.mul(x,x)")
print(torch.mul(x,x))

Original Matrix
tensor([[0.5171, 0.3085, 0.3660],
        [0.7481, 0.6085, 0.4808],
        [0.4394, 0.9441, 0.4091],
        [0.4761, 0.6302, 0.1447],
        [0.4793, 0.8272, 0.0664]])
Output of performing x**2
tensor([[0.2674, 0.0952, 0.1339],
        [0.5597, 0.3703, 0.2312],
        [0.1930, 0.8914, 0.1674],
        [0.2267, 0.3972, 0.0209],
        [0.2297, 0.6842, 0.0044]])
Output of performing x*x
tensor([[0.2674, 0.0952, 0.1339],
        [0.5597, 0.3703, 0.2312],
        [0.1930, 0.8914, 0.1674],
        [0.2267, 0.3972, 0.0209],
        [0.2297, 0.6842, 0.0044]])
Output of performing torch.mul(x,x)
tensor([[0.2674, 0.0952, 0.1339],
        [0.5597, 0.3703, 0.2312],
        [0.1930, 0.8914, 0.1674],
        [0.2267, 0.3972, 0.0209],
        [0.2297, 0.6842, 0.0044]])


In [9]:
# Square Root of a Tensor
x = torch.rand(5, 3)
print("Original Matrix")
print(x)
print("Output torch.sqrt(x)")
# Also converting the final result tensor to a numpy array
print(torch.sqrt(x).numpy())

Original Matrix
tensor([[0.5349, 0.7074, 0.4162],
        [0.7517, 0.6515, 0.6553],
        [0.5924, 0.8421, 0.9170],
        [0.1435, 0.2997, 0.0393],
        [0.8689, 0.7978, 0.7075]])
Output torch.sqrt(x)
[[0.7313988  0.8410847  0.6451696 ]
 [0.8669845  0.807185   0.80953074]
 [0.7696525  0.9176361  0.9576139 ]
 [0.37882388 0.5474616  0.19829525]
 [0.932167   0.8932035  0.841157  ]]
